
## Run batches of R scripts. Handy if you want scripts to run after another finishes while you're away from the machine

purrr::walk(c(                                            
  # "./R scripts/sediment.00 DOMAINS.R",
  # "./R scripts/sediment.01 GRID WATER.R",
  # "./R scripts/sediment.02 CROP SINMOD.R", 
  # "./R scripts/sediment.03 CROP WAVES.R",
  # "./R scripts/sediment.04 WATER TS.R",
  # "./R scripts/sediment.05 INTERPOLATE WAVES.R",
  # "./R scripts/sediment.06 EXPAND.R",
  # "./R scripts/sediment.07 SHEARSTRESS.R",
  # "./R scripts/sediment.08 RF PREDICTORS.R",
  # "./R scripts/sediment.09 H2O.R",
  # "./R scripts/sediment.10 SEDIMENT FRACTIONS.R",
  # "./R scripts/sediment.11 WRITE CSV.R",
  # "./R scripts/sediment.12 NITROGEN CONTENT.R",
  # "./R scripts/sediment.13 CARBON CONTENT.R",
  # "./R scripts/sediment.14 PERM PORE.R",
  # "./R scripts/sediment.15 WRITE NETCDF.R",
  # "./R scripts/sediment.16 SEASONAL STRESS.R",
  # "./R scripts/sediment.17 DAILY DISTURBANCE.R",
  # "./R scripts/sediment.18 RASTERISE DISTURBANCE.R",
  # "./R scripts/sediment.19 SEASONAL DISTURBANCE.R",
  # "./R scripts/sediment.20 ZONAL SUMMARIES.R",
  # "./R scripts/figure.0 MAP BACKGROUND.R",
  # "./R scripts/figure.1 MAP DOMAIN.R",
  # "./R scripts/figure.2 SCHEMATIC.R",
   "./R scripts/figure.4 SEDIMENT FRACTIONS.R",
   "./R scripts/figure.5 D50.R",
   "./R scripts/figure.6 PERMEABILITY AND POROSITY.R",
   "./R scripts/figure.7 OMC.R",
   "./R scripts/figure.8 STRESS AND DISTURBANCE.R",
   "./R scripts/figure.supplementary SEASONAL.R"
), MiMeMo.tools::execute)
